### ISSUE TITLE
v3.5.1 introduced PHP parse error

### ISSUE THREAD

**Issue by Scott-takealot** [queueit/KnownUser.V3.PHP#11]
Using PHP 5.3.10 the following error is produced: 

PHP message: PHP Parse error:  syntax error, unexpected '['

Version 3.5.0 does not have this issue.

**Comment by frwiqueueit** [comment]
Thank you Scott. We will fix the issue.

**Comment by frwiqueueit** [comment]
Fixed in release 3.5.2.
