### ISSUE TITLE
Update readme stressing importance of caching configuration and clearly defining requirements

### ISSUE THREAD

**Issue by JoshuaCrittenden** [queueit/KnownUser.V3.PHP#13]
In the further documentation linked to in the readme you have  regarding queue-it configuration fetching from portal:
> It is recommended to make a timer function that can download and cache the configuration for e.g. 5-10 minutes.

I strongly suggest you update that to clearly indicate that requests must be cached, else your IP(s) will be blacklisted after n requests beyond a freshold without warning - which has happened to a client of mine. I've subsequently had to discuss this with queue-it support to get clarity on minimum cache TTL and allowed frequency of requests per IP etc. I will have to update their implementation accordingly and perhaps other users of KnownUser.V3.PHP will have to too if they've also not cached prematurely.

Best,
Josh

**Comment by queueit** [comment]
Thank you Joshua,
We will update the documentation to be more clear on why caching is important.

**Comment by frwiqueueit** [comment]
We have updated all documentation
