### ISSUE TITLE
Typo in Documentation

### ISSUE THREAD

**Issue by adamjakab** [queueit/KnownUser.V3.PHP#16]
in the curl instruction - there is an extra `'` in:

> curl --request GET https://[your-customer-id].queue-it.net/status/integrationconfig/secure/[your-customer-id]' --header 'api-key: [Customer API-Key]' --header 'Host: queue-it.net'

This was already reported on the LUA repo [here](https://github.com/queueit/KnownUser.V3.Lua/issues/3), so it might be worth reviewing all the KU repositories as it seems like a copy&paste error.

**Comment by frwiqueueit** [comment]
Thanks, we will go through all the repos documentation
