### ISSUE TITLE
convert PNG to png

### ISSUE THREAD

**Issue by gemal** [queueit/KnownUser.V3.PHP#3]
in the Documentation folder please use "png" and not "PNG" as extensions for the images

PNG files are detected as text in git
png files are detected as binary in git

when used in other systems

**Comment by frwiqueueit** [comment]
Thank you. We will update.

**Comment by gemal** [comment]
Could you make a new release this for us to pick it up?

**Comment by frwiqueueit** [comment]
I did not change any code just images, so why would you like to update?

**Comment by gemal** [comment]
we rely on the code in our repo so when we do a composer update the files gets updated and right now we had issues with the PNG files saying they are modified due to the line endings in the files.
so we a new release this issue would be fixed at us

**Comment by frwiqueueit** [comment]
OK, thanks for clarification. I will make a release.
