### ISSUE TITLE
default locale when sending to queue

### ISSUE THREAD

**Issue by gemal** [queueit/KnownUser.V3.PHP#4]
we have a website which include a locale in the URL
so when we send people to the queue we know the locale that the user should get the queue language in.
Is there a parameter for us to use for setting the correct default language in the queue?

Fx a user enters our site:
https://site.com/en-US
we send people to the queue but how do we specifcy that the default language should be "en-US" ?

**Comment by sarooghi** [comment]
1-Define two different URL triggers based on language query string part.
2-Define two different actions with the same event and different languages and attach the relevant triggers to actions.
