### ISSUE TITLE
Example of `integrationconfig.json` format

### ISSUE THREAD

**Issue by kenorb** [queueit/KnownUser.V3.PHP#8]
The code in Implementation section loads the `integrationconfig.json` file as per:

> If we have the `integrationconfig.json` copied in the folder beside other knownuser files inside web application folder.

Where I can find the documentation how this file format should look like?

**Comment by sarooghi** [comment]
Actually, you do not need to know the format it is an auto-generated file.This file will get generated for you when you publish your configuration from Queue-it go platform.
After setting up your integration configuration using Queue-it Go platform you can download the file from https://[your-customer-id].queue-it.net/status/integrationconfig/[your-customer-id] URL, please contact Queue-it support if you needed more information how to config your integration in Go platform.
