### ISSUE TITLE
CookieManagerMock bug

### ISSUE THREAD

**Issue by gemal** [queueit/KnownUser.V3.PHP#9]
When I run composer update I sometimes get this in my `autoload_classmap.php` file:
`'CookieManagerMock' => $vendorDir . '/queueit/knownuserv3/Tests/IntegrationConfigHelpersTest.php',`

and sometimes this:
`'CookieManagerMock' => $vendorDir . '/queueit/knownuserv3/Tests/KnownUserTest.php',`

I think composer is getting confused because CookieManagerMock class exists in both files IntegrationConfigHelpersTest.php and KnownUserTest.php.

**Comment by frwiqueueit** [comment]
Thank you, Henrik.
We will look into this for the next release.

**Comment by gemal** [comment]
Thank you

**Comment by frwiqueueit** [comment]
Fixed in release 3.5.2.
